# Based on tutorial, https://github.com/pypa/gh-action-pypi-publish
name: Build library
on: [ push ]

jobs:
  publish-and-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: build
      url: https://pypi.org/p/divert
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment `3.10`
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Build
        run: python -m build

      - name: Publish package distributions to PyPI
        if: github.ref == 'refs/heads/main'  # Only upload if change was to the main branch
        uses: pypa/gh-action-pypi-publish@release/v1
