# Based on tutorial, https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Lint and test library
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt

      - name: Lint
        run: ruff --format=github .

      - name: Run tests
        run: pytest
